'''
Node wise Expression Handlers
'''
from static_analysis.abstract_collecting_semantics.builder.nodes import ExpressionStatement
from static_analysis.abstract_collecting_semantics.builder.nodes import VariableDeclarationStatement
from static_analysis.abstract_collecting_semantics.builder.nodes import WhileStatement
from static_analysis.abstract_collecting_semantics.builder.nodes import DoWhileStatement
from static_analysis.abstract_collecting_semantics.builder.nodes import ForStatement
from static_analysis.abstract_collecting_semantics.builder.nodes import IfStatement
